name: equipo2
channels:
    - defaults
dependencies:
    - bzip2=1.0.8
    - ca-certificates=2023.01.10
    - certifi=2022.12.7
    - libffi=3.4.2
    - openssl=1.1.1t
    - pip=23.0.1
    - python=3.10.9
    - setuptools=65.6.3
    - sqlite=3.40.1
    - tk=8.6.12
    - vc=14.2
    - vs2015_runtime=14.27.29016
    - wheel=0.38.4
    - wincertstore=0.2
    - xz=5.2.10
    - zlib=1.2.13
    - pip:
          - altair==4.2.2
          - attrs==22.2.0
          - blinker==1.5
          - click==8.1.3
          - colorama==0.4.6
          - decorator==5.1.1
          - entrypoints==0.4
          - gitdb==4.0.10
          - gitpython==3.1.31
          - google-api-core==2.11.0
          - google-api-python-client==2.80.0
          - google-auth-httplib2==0.1.0
          - google-auth-oauthlib==1.0.0
          - googleapis-common-protos==1.58.0
          - httplib2==0.21.0
          - importlib-metadata==6.0.0
          - jinja2==3.1.2
          - jsonschema==4.17.3
          - markdown-it-py==2.2.0
          - mdurl==0.1.2
          - packaging==23.0
          - pillow==9.4.0
          - pyarrow==11.0.0
          - pydeck==0.8.0
          - pygments==2.14.0
          - pympler==1.0.1
          - pyparsing==3.0.9
          - pyrsistent==0.19.3
          - pytz-deprecation-shim==0.1.0.post0
          - rich==13.3.2
          - semver==2.13.0
          - smmap==5.0.0
          - streamlit==1.19.0
          - toml==0.10.2
          - toolz==0.12.0
          - tornado==6.2
          - typing-extensions==4.5.0
          - tzdata==2022.7
          - tzlocal==4.2
          - uritemplate==4.1.1
          - validators==0.20.0
          - watchdog==2.3.1
          - zipp==3.15.0
